/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KASIR;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;

/**
 *
 * @author PC-HP
 */
public class FormHarga extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;
    
    /**
     * Creates new form FormHarga
     */
    public FormHarga() {
        initComponents();
        tampilkandata();
        
    }
    
    public void tampilkandata() {
        DefaultTableModel tabelharga = new DefaultTableModel();
        tabelharga.addColumn("LANGGANAN");
        tabelharga.addColumn("ECERAN");
    
        try {
            String sql = "select * from harga";
            // Pastikan nama class koneksi benar (Koneksi atau KoneksiDatabase)
            java.sql.Connection conn = Koneksi.getConnection(); 
            java.sql.Statement stat = conn.createStatement();
            java.sql.ResultSet res = stat.executeQuery(sql);
        
            while (res.next()) {
                // 1. Ambil data mentah (misal: "100000")
                String hargaL = res.getString("langganan");
                String hargaE = res.getString("eceran");
            
                // 2. Format jadi Rupiah (misal: "Rp 100.000")
                // Pastikan fungsi helper 'formatRupiah' sudah ada di bawah
                String formatL = formatRupiah(hargaL);
                String formatE = formatRupiah(hargaE);
            
                // 3. Masukkan ke tabel
                // PERBAIKAN: Gunakan 'tabelharga', bukan 'model'
                // PERBAIKAN: Syntax array yang benar adalah new Object[] {...}
                tabelharga.addRow(new Object[] { formatL, formatE });
            }
        
            // Pasang model ke JTable di layar
            tblHarga.setModel(tabelharga);
        
            } catch (Exception e) {
            // Tampilkan error agar tahu jika ada masalah
            javax.swing.JOptionPane.showMessageDialog(this, "Error Tampil Data: " + e.getMessage());
        }
    }
    
    private String formatRupiah(String angka) {
        if (angka == null || angka.isEmpty()) {
            return "";
        }
        
        String bersih = angka.replaceAll("[^\\d]", "");
        
        if (bersih.isEmpty()) {
            return "";
        }
        
        try {
            long value = Long.parseLong(bersih);
            java.text.DecimalFormat kursIndo = (java.text.DecimalFormat) java.text.DecimalFormat.getCurrencyInstance();
            java.text.DecimalFormatSymbols formatRP  = new java.text.DecimalFormatSymbols();
            
            formatRP.setCurrencySymbol("Rp ");
            formatRP.setMonetaryDecimalSeparator(',');
            formatRP.setGroupingSeparator('.');
            
            kursIndo.setDecimalFormatSymbols(formatRP);
            kursIndo.setMaximumFractionDigits(0);
            
            return kursIndo.format(value);
            
        } catch (NumberFormatException e) {
            return "";
        }
    }

// 2. Fungsi untuk membersihkan format saat mau disimpan (Rp 10.000 -> 10000)
private String bersihkanRupiah(String angka) {
    if (angka == null || angka.isEmpty()) return "0";
    return angka.replaceAll("[^0-9]", "");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLangganan = new javax.swing.JTextField();
        txtEceran = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHarga = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HARGA - SIRKULASI");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA HARGA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setText("HARGA LANGGANAN");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setText("HARGA ECERAN");

        txtLangganan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLanggananKeyReleased(evt);
            }
        });

        txtEceran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEceranKeyReleased(evt);
            }
        });

        tblHarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHargaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHarga);

        btnTambah.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKembali.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEceran)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLangganan, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLangganan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEceran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKembali))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblHargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHargaMouseClicked
        int baris = tblHarga.getSelectedRow();

        String langganan = tblHarga.getValueAt(baris, 0).toString();
        String eceran = tblHarga.getValueAt(baris, 1).toString();

        txtLangganan.setText(langganan);
        txtEceran.setText(eceran);
    }//GEN-LAST:event_tblHargaMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String langganan = txtLangganan.getText();
        String eceran = txtEceran.getText();

        if (langganan.isEmpty()||eceran.isEmpty()){
            JOptionPane.showMessageDialog(this,"Mohon Isi Seluruh Fieldnya", "HARAP ISI !!!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String sql = "INSERT INTO harga (langganan, eceran) VALUES (?,?)";

            Connection conn = Koneksi.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            
            String langgananBersih = bersihkanRupiah(txtLangganan.getText());
            String eceranBersih = bersihkanRupiah(txtEceran.getText());

            ps.setString(1, langgananBersih);
            ps.setString(2, eceranBersih);

            int hasil = ps.executeUpdate();

            if (hasil>0) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
                tampilkandata();
                txtLangganan.setText("");
                txtEceran.setText("");
            }
        }catch (java.sql.SQLException e){
            JOptionPane.showMessageDialog(this, "Gagal Memasukkan Data Wilayah" + e.getMessage());
        };
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            String sql = "UPDATE harga SET eceran=? WHERE langganan=?";
            Connection conn = Koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            
            String eceranRaw = txtEceran.getText();
            String langgananRaw = txtLangganan.getText();
            
            String eceranBersih = bersihkanRupiah(eceranRaw);
            String langgananBersih = bersihkanRupiah(langgananRaw);
            
            pst.setString(1, eceranBersih);
            pst.setString(2, langgananBersih);
            int updated = pst.executeUpdate();

            if (updated > 0) {
                JOptionPane.showMessageDialog(null, "Data Telah Di Update");
                tampilkandata();
                txtLangganan.setText("");
                txtEceran.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Data Gagal Di Update");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (txtLangganan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih Data Dari Tabel Terlebih Dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus data harga: " + txtLangganan.getText() + " ?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                String sql = "DELETE FROM harga WHERE langganan = ?";
                
                java.sql.Connection conn = Koneksi.getConnection();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                
                String idBersih = bersihkanRupiah(txtLangganan.getText());
                pst.setString(1, idBersih);
                
                int rowsAffected = pst.executeUpdate();
                
                if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                tampilkandata(); // Refresh tabel
                
                // Kosongkan form setelah hapus
                txtLangganan.setText("");
                txtEceran.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal Menghapus (Data tidak ditemukan di database)");
                }            
            }catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new FormSirkulasi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtLanggananKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLanggananKeyReleased
        // Ambil text yang sedang diketik
    String input = txtLangganan.getText();
    
    // Jangan proses jika kosong
    if (input.isEmpty()) return;
    
    // Ubah jadi format rupiah
    String hasil = formatRupiah(input);
    
    // Pasang kembali ke text field
    txtLangganan.setText(hasil);
    }//GEN-LAST:event_txtLanggananKeyReleased

    private void txtEceranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEceranKeyReleased
        String input = txtEceran.getText();
    
    // Jangan proses jika kosong
    if (input.isEmpty()) return;
    
    // Ubah jadi format rupiah
    String hasil = formatRupiah(input);
    
    // Pasang kembali ke text field
    txtEceran.setText(hasil);
    }//GEN-LAST:event_txtEceranKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHarga;
    private javax.swing.JTextField txtEceran;
    private javax.swing.JTextField txtLangganan;
    // End of variables declaration//GEN-END:variables
}
