/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KASIR;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.*;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PC-HP
 */
public class FormTanggalTerbit extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;
    
    String tglLama = "";
    /**
     * Creates new form FormTanggalTerbit
     */
    public FormTanggalTerbit() {
        initComponents();
        tampilkandata();
    }
    
    public void tampilkandata() {
        DefaultTableModel tabeldataterbit = new DefaultTableModel();
        tabeldataterbit.addColumn("TANGGAL TERBIT");
        tabeldataterbit.addColumn("OPLAH");
        tabeldataterbit.addColumn("CETAK");
        tabeldataterbit.addColumn("TANGGAL TUTUP");
        
        try {
            String sql = "select * from tglterbit";
            Connection conn = Koneksi.getConnection();
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while (res.next()) {
                tabeldataterbit.addRow(new Object[]{res.getString(1), res.getString(2),res.getString(3),res.getString(4)});
            }
            tblTanggalTerbit.setModel(tabeldataterbit);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTanggalTerbit = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtOplah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCetak = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        dateTerbit = new com.toedter.calendar.JDateChooser();
        dateTutup = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA TANGGAL TERBIT");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setText("TANGGAL TERBIT");

        tblTanggalTerbit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTanggalTerbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTanggalTerbitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTanggalTerbit);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setText("OPLAH");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setText("CETAK");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setText("DITUTUP");

        btnTambah.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKembali.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOplah, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtCetak)
                            .addComponent(dateTerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(dateTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtOplah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCetak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dateTutup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKembali))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblTanggalTerbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTanggalTerbitMouseClicked
        try {
            int baris = tblTanggalTerbit.getSelectedRow();
            
            String tglTerbitStr = tblTanggalTerbit.getValueAt(baris, 0).toString();
            String oplah = tblTanggalTerbit.getValueAt(baris, 1).toString();
            String cetak = tblTanggalTerbit.getValueAt(baris, 2).toString();
            String tglTutupStr = tblTanggalTerbit.getValueAt(baris, 3).toString();
            
            txtOplah.setText(oplah);
            txtCetak.setText(cetak);
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            
            Date dateTerbitObj = sdf.parse(tglTerbitStr);
            Date dateTutupObj = sdf.parse(tglTutupStr);
            
            dateTerbit.setDate(dateTerbitObj);
            dateTutup.setDate(dateTutupObj);
            
            tglLama = tglTerbitStr;
            
        } catch (Exception e) {
            System.out.println("Error Klik Tabel: " + e.getMessage());
        }
        
    }//GEN-LAST:event_tblTanggalTerbitMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String oplah = txtOplah.getText().trim();
        String cetak = txtCetak.getText().trim();
        
        if (dateTerbit == null || dateTutup == null || oplah.isEmpty()||cetak.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon isi semua field !", "Peringatan",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyyy-MM-dd");
            String tglTerbit = sdf.format(dateTerbit.getDate());
            String tglTutup = sdf.format(dateTutup.getDate());
            
            String sql = "INSERT INTO tglterbit (tglterbit,oplah,cetak,tgltutup) VALUES (?,?,?,?)";
            
            Connection conn = Koneksi.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, tglTerbit);
            ps.setString(2, oplah);
            ps.setString(3, cetak);
            ps.setString(4, tglTutup);
            
            int hasil = ps.executeUpdate();
            
            if (hasil>0) {
                JOptionPane.showMessageDialog(this, "Data Berhasil DI tambahkan");
                tampilkandata();
                
                dateTerbit.setDate(null);
                txtOplah.setText("");
                txtCetak.setText("");
                dateTutup.setDate(null);
            }
            
        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal Simpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (tglLama.equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data dari tabel terlebih dahulu!");
            return;
        }
        
        if (dateTerbit.getDate() == null || dateTutup.getDate() == null || txtOplah.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Lengkapi semua data!");
        return;
        }
        
        try {
        // 3. Siapkan Format Tanggal
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        String tglTerbitBaru = sdf.format(dateTerbit.getDate());
        String tglTutupBaru = sdf.format(dateTutup.getDate());
        String oplahBaru = txtOplah.getText();
        String cetakBaru = txtCetak.getText();

        // 4. Query SQL UPDATE
        // "Ubah data jadi baru, KHUSUS UNTUK data yang tanggal terbitnya = tglLama"
        String sql = "UPDATE tglterbit SET tglterbit=?, tgltutup=?, oplah=?, cetak=? WHERE tglterbit=?";
        
        java.sql.Connection conn = Koneksi.getConnection();
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);

        // 5. Masukkan Parameter
        ps.setString(1, tglTerbitBaru);
        ps.setString(2, tglTutupBaru);
        ps.setString(3, oplahBaru);
        ps.setString(4, cetakBaru);
        
        // Parameter ke-5 adalah KUNCI (WHERE)
        ps.setString(5, tglLama); 

        int hasil = ps.executeUpdate();

        if (hasil > 0) {
            JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate");
            tampilkandata();
            
            // Reset Form & Variabel Kunci
            dateTerbit.setDate(null);
            dateTutup.setDate(null);
            txtOplah.setText("");
            txtCetak.setText("");
            tglLama = ""; // Kosongkan kunci lagi
        } else {
            JOptionPane.showMessageDialog(this, "Gagal Update. Data lama tidak ditemukan.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error Edit: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // 1. Cek apakah user sudah klik tabel? (tglLama harus ada isinya)
    if (tglLama.equals("")) {
        JOptionPane.showMessageDialog(this, "Silakan pilih data yang akan dihapus dari tabel!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Konfirmasi Hapus (Agar tidak terhapus tidak sengaja)
    int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menghapus data terbitan tanggal: " + tglLama + " ?",
            "Konfirmasi Hapus", 
            JOptionPane.YES_NO_OPTION);

    // Jika User pilih YES
    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            // 3. Query SQL DELETE
            // "Hapus data DARI tabel data_terbit DIMANA tanggal_terbitnya adalah tglLama"
            String sql = "DELETE FROM tglterbit WHERE tglterbit = ?";
            
            java.sql.Connection conn = Koneksi.getConnection();
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            
            // Masukkan Parameter Kunci
            ps.setString(1, tglLama);
            
            int hasil = ps.executeUpdate();
            
            if (hasil > 0) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                tampilkandata(); // Refresh tabel
                
                // 4. Reset Form & Variabel Kunci
                dateTerbit.setDate(null);
                dateTutup.setDate(null);
                txtOplah.setText("");
                txtCetak.setText("");
                tglLama = ""; // Penting: Kosongkan kunci lagi
            } else {
                JOptionPane.showMessageDialog(this, "Gagal Hapus. Data tidak ditemukan di database.");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Hapus: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new FormSirkulasi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTanggalTerbit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTanggalTerbit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTanggalTerbit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTanggalTerbit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTanggalTerbit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private com.toedter.calendar.JDateChooser dateTerbit;
    private com.toedter.calendar.JDateChooser dateTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTanggalTerbit;
    private javax.swing.JTextField txtCetak;
    private javax.swing.JTextField txtOplah;
    // End of variables declaration//GEN-END:variables
}
